<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Modules.Ordering.Domain\ECommerce.Modules.Ordering.Domain.csproj" />
    <ProjectReference Include="..\ECommerce.Modules.Ordering.Contracts\ECommerce.Modules.Ordering.Contracts.csproj" />
    <ProjectReference Include="..\..\Cart\ECommerce.Modules.Cart.Contracts\ECommerce.Modules.Cart.Contracts.csproj" />
    <ProjectReference Include="..\..\Inventory\ECommerce.Modules.Inventory.Contracts\ECommerce.Modules.Inventory.Contracts.csproj" />
    <ProjectReference Include="..\..\Payments\ECommerce.Modules.Payments.Contracts\ECommerce.Modules.Payments.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Common\ECommerce.Common.Application\ECommerce.Common.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
