<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Modules.Inventory.Application\ECommerce.Modules.Inventory.Application.csproj" />
    <ProjectReference Include="..\ECommerce.Modules.Inventory.Contracts\ECommerce.Modules.Inventory.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Common\ECommerce.Common.Presentation\ECommerce.Common.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
